### ISSUE TITLE
Crash on FreeBSD when trying to run

### ISSUE THREAD

**Issue by Thurinum** [theodore-lheureux/cantgoogleit-client#1]
I am trying to run cantgoogleit on a FreeBSD 9.3 machine with node 0.10.48 installed. However, whenever I try to execute the command node index.js, I get the following error:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory Abort trap Get better (core dumped)`

I checked the core dump file and found that there was a heap underflow in the V8 engine, which caused the kernel garbage collection to corrupt some memory pages. I suspect that this is related to the outdated node version that I am using, since cantgoogleit requires node 12 or higher.

Is there any way to fix this issue without upgrading my node version or my FreeBSD system? I have some legacy applications that depend on these versions and I cannot afford to break them. Any help would be appreciated. Thanks.

**Comment by theodore-lheureux** [comment]
get arch

**Comment by Thurinum** [comment]
Dear Theodore,

I want to express my sincere gratitude for introducing me to arch linux. It has been a life-changing experience for me. Arch linux has taught me so much about the inner workings of a computer system, the power of customization, and the joy of learning new things. I have never felt more in control of my own device and more confident in my technical skills. Arch linux has also opened up a whole new world of possibilities for me, as I can now explore various applications, tools, and projects that I could not access before. I am amazed by the vibrant and supportive community of arch linux users, who are always ready to help and share their knowledge. Thanks to you, I have discovered a new passion and a new hobby that I enjoy immensely. You have truly changed my life for the better. 

Thank you so much for your generosity and guidance!
